### ISSUE TITLE
Make HTTP requests asynchronous

### ISSUE THREAD

**Issue by AntoniosBarotsis** [AntoniosBarotsis/Rss2Email#18]
Currently, the web feeds are fetched synchronously [here](https://github.com/AntoniosBarotsis/Rss2Email/blob/5be46c0240259357394c58a91e45683bd168ee7b/src/lib.rs#L17-L53). There should be quite a significant speedup if this was done asynchronously.

I recommend using something like [hyperfine](https://github.com/sharkdp/hyperfine) to make a before and after performance comparison.
For me, each run takes around 15 seconds. 

```sh
➜ hyperfine 'cargo run' -r 3
Benchmark 1: cargo run
  Time (mean ± σ):     16.443 s ±  0.410 s    [User: 4.863 s, System: 0.156 s]
  Range (min … max):   16.117 s … 16.904 s    3 runs
```

If someone wants to work on this, I can post the feeds I am using. If someone does pick this up, make sure to post your before and after benchmarks in your merge request.

**Comment by techrajdeep** [comment]
I am looking for an issue for my first contribution . Can you help me here. Can I take on this .

**Comment by AntoniosBarotsis** [comment]
This is already being worked at in #19. I feel like it's probably not the best first issue as it is a bit complicated, sorry!
