### ISSUE TITLE
Read `feeds` from environment variables [Rust]

### ISSUE THREAD

**Issue by AntoniosBarotsis** [AntoniosBarotsis/Rss2Email#7]
Currently, the feeds are being read from a local text file [here](https://github.com/AntoniosBarotsis/Rss2Email/blob/fb913b3fd6fd9e860677abb27d81ef9800977195/src/util.rs#L58). This is a rather bad design choice as you might want to add new feeds quite often. It is especially annoying if you have deployed this as a docker image since you need to rebuild it (even though that is fast because of caching).

A new function should be created that first attempts to read the feeds from an environment variable. If that is not found or is empty, it should try to read from the file as it is doing now.

The format of the env variable contents is up for discussion but I feel like a line of semicolon-delimited links would suffice (so `[link];[other link]`.

**Comment by oliviacarino** [comment]
Hey, can I take this on for Hacktoberfest?

**Comment by AntoniosBarotsis** [comment]
Yes! Let me know if you have any questions!

**Comment by Kineolyan** [comment]
Hello @AntoniosBarotsis,

As your initial problem stems from the need to customize your container after a build, you can rewrite it a bit to use Docker volumes instead. If interesting, I made a draft PR for this in #13 .

**Comment by oliviacarino** [comment]
@AntoniosBarotsis would an example of user input be: https://antoniosbarotsis.github.io/index.xml;https://github.blog/feed

I used ; as the delimiter for each link

**Comment by AntoniosBarotsis** [comment]
Yes!

**Comment by oliviacarino** [comment]
Submitted a PR! https://github.com/AntoniosBarotsis/Rss2Email/pull/16
