### ISSUE TITLE
Performance investigation [Rust]

### ISSUE THREAD

**Issue by AntoniosBarotsis** [AntoniosBarotsis/Rss2Email#8]
Currently, this project is not Blazingly Fast 🚀 (despite the fact that it is written in Rust). An investigation to reveal what parts of the code make it slower would be pretty useful.

You can use something like [Criterion](https://github.com/bheisler/criterion.rs).

Keep in mind that the issue is for just the investigation! Changes are not really included in this (as for that I'd have to consider things like extra dependencies and whatnot). Creating the benchmarks and making a simple report is enough for this. In the case that an easy and important optimization is determined, after discussed I could definitely make this a separate issue.

**Comment by ddanielsantos** [comment]
Hi, I was reading about Criterion and I think I can do this one.

Is this issue still available?

**Comment by AntoniosBarotsis** [comment]
Yup! Feel free to ask any questions you may have!
