### ISSUE TITLE
Writing tests [Rust]

### ISSUE THREAD

**Issue by AntoniosBarotsis** [AntoniosBarotsis/Rss2Email#9]
There are currently no tests present in the project. While it is very easy to test manually, automated tests are definitely quite handy.

I'm interested in testing that downloading and parsing (separately) RSS feeds are working properly. There should be a way to define a list of feeds to be used in these tests. 

Feel free to make any additional tests!

Adding automated code coverage reports would also be a very much welcome addition.

**Comment by Kineolyan** [comment]
Hello @AntoniosBarotsis, if that's ok with you, I would be interesting to work on this issue as part of the Hacktoberfest.
I plan to start with the two tasks you mention and see what to do next as I dive into the codebase.

One question I am asking myself for which I did not find an answer in your README or CONTRIBUTING: what is your standard workflow for running this?
I see that you have a main version launching it and an aws flavor.
Though that should not impact my ability to write tests, I am curious.

Cheers

**Comment by AntoniosBarotsis** [comment]
Hello!

Yes I think I do not mention this explicitly but a `cargo run` will run the code as you'd expect **without**$^1$ sending an email (or requiring the relevant credentials), if you instead run this in release, then the email would also be sent.

The AWS-Lambda stuff you can ignore as the only thing that changes is some boilerplate around the main function.

1: Halfway through writing this I realized that I actually try to resolve the API key early which I shouldn't do, I'll push a commit fixing that in a few minutes and I'll try to include the basic outline of running the app in the contributing file 

Let me know if you have any other questions :)

**Comment by AntoniosBarotsis** [comment]
I made a few tweaks to the [`README`](https://github.com/AntoniosBarotsis/Rss2Email/blob/master/README.md) and [`CONTRIBUTING`](https://github.com/AntoniosBarotsis/Rss2Email/blob/master/CONTRIBUTING.md) files as well as the [Wiki](https://github.com/AntoniosBarotsis/Rss2Email/wiki), let me know if its more clear now!

**Comment by Kineolyan** [comment]
Looks clear enough. Thanks for the update.
I will dive in the code tomorrow, as it is time for me to sleep :smile:

**Comment by Kineolyan** [comment]
Hello @AntoniosBarotsis, I have started another branch for parsing tests https://github.com/Kineolyan/Rss2Email/tree/add-tests-for-parsing

I already have tests for the parsing of Atom feeds and hope to work on RSS this week. Unlike the previous PR I made, that focused on download, I wanted to cover the whole topic before submitting a PR :)

**Comment by AntoniosBarotsis** [comment]
That's totally fine and thanks for yet another contribution! I was just going over some issues and wanted to make sure that this is still open :)

**Comment by Kineolyan** [comment]
Hello @AntoniosBarotsis,

I have a question about RSS. The spec for RSS 0.91 [1] and RSS 0.92 [2] does not define any date for the entries. There is one date at the level of the channel but representing the update date of the whole file.
Given that your goal is to only retrieve the last posts of blogs, I would say that you do not want to support those specs.
Currently, they are not supported because serde parsing will fail. I can simply write tests specifying this for the record. Or do you prefer I update the parsing logic to support those two formats?

[1] https://www.rssboard.org/rss-0-9-1
[2] https://www.rssboard.org/rss-0-9-2
